//
// CatBreedsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class CatBreedsAPI {
    /**
     Returns a list of cat breeds
     
     - parameter attachBreed: (query)  (optional, default to 0)
     - parameter page: (query)  (optional)
     - parameter limit: (query)  (optional)
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCatBreedList(attachBreed: Int? = nil, page: Int? = nil, limit: Int? = nil, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: [CatBreed]?,_ error: Error?) -> Void)) {
        getCatBreedListWithRequestBuilder(attachBreed: attachBreed, page: page, limit: limit).execute(apiResponseQueue) { result -> Void in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Returns a list of cat breeds
     - GET /breeds
     - responseHeaders: [Pagination-Count(Int), Pagination-Page(Int), Pagination-Limit(Int)]
     - parameter attachBreed: (query)  (optional, default to 0)
     - parameter page: (query)  (optional)
     - parameter limit: (query)  (optional)
     - returns: RequestBuilder<[CatBreed]> 
     */
    open class func getCatBreedListWithRequestBuilder(attachBreed: Int? = nil, page: Int? = nil, limit: Int? = nil) -> RequestBuilder<[CatBreed]> {
        let path = "/breeds"
        let URLString = "https://api.thecatapi.com/v1" + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "attach_breed": attachBreed?.encodeToJSON(), 
            "page": page?.encodeToJSON(), 
            "limit": limit?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<[CatBreed]>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
