//
// CatBreedWeight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CatBreedWeight: Codable {

    public var imperial: String?
    public var metric: String?

    public init(imperial: String? = nil, metric: String? = nil) {
        self.imperial = imperial
        self.metric = metric
    }

}

