//
// CatBreedImage.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CatBreedImage: Codable {

    public var id: String?
    public var width: Double?
    public var height: Double?
    public var url: String?

    public init(id: String, width: Double? = nil, height: Double? = nil, url: String? = nil) {
        self.id = id
        self.width = width
        self.height = height
        self.url = url
    }

}

